stages:
  - Build
  - Upload
  - Release

build:
  stage: Build
  image: electronuserland/builder:wine
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - release/