stages:
  - build
  - upload
  - release

build-windows:
  stage: build
  image: electronuserland/builder:wine
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - release/