stages:
  - test
  - build
  - release

lint:
  stage: test
  image: node:22
  before_script:
    - echo "@fklab:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm install
  script:
    - npm run lint

build-windows:
  stage: build
  image: electronuserland/builder:wine
  before_script:
    - echo "@fklab:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm install
  script:
    - npm run build-win
  only:
    - tags
  artifacts:
    paths:
      - release/*.*
    exclude:
      - release/*.blockmap
      - release/*.yml

build-linux:
  stage: build
  image: node:22
  before_script:
    - echo "@fklab:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - apt-get update -y && apt-get install -y libgtk-3-dev libxss1 libasound2
    - npm install
  script:
    - npm run build-linux
  only:
    - tags
  artifacts:
    paths:
      - release/*.*
    exclude:
      - release/*.yml
